name: Main CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: sample

    steps:
    - uses: actions/checkout@v1

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/$APP_NAME:${GITHUB_SHA::7}

    - name: Push the Docker image
      run: docker push docker.pkg.github.com/${{ github.repository }}/$APP_NAME:${GITHUB_SHA::7}

    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
        images: |
          docker.pkg.github.com/${{ github.repository }}/$APP_NAME:${GITHUB_SHA::7}
