name: Main CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: sample
      ACTIONS_STEP_DEBUG: true

    steps:
    - uses: actions/checkout@v1

   # - name: Login to GitHub Package Registry
   #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag docker.pkg.github.com/kaluzaaa/sample-net-core-docker-actions-package-registry/sample:${{ github.sha }}

    #- name: Push the Docker image
     # run: docker push docker.pkg.github.com/kaluzaaa/sample-net-core-docker-actions-package-registry/sample:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: docker.pkg.github.com
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
          manifests/ingress.yaml
        images: 'docker.pkg.github.com/kaluzaaa/sample-net-core-docker-actions-package-registry/sample:tojesttest'
        imagepullsecrets: 'demo-k8s-secret'
