name: Main CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/kaluzaaa/registry-test/my-image-name:${GITHUB_SHA::7}

    - name: Push the Docker image
      run: docker push docker.pkg.github.com/kaluzaaa/registry-test/my-image-name:${GITHUB_SHA::7}
