name: Main CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/sample

    steps:
    - uses: actions/checkout@v1

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:${GITHUB_SHA::7}

    - name: Push the Docker image
      run: docker push $IMAGE:${GITHUB_SHA::7}

    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: docker.pkg.github.com
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - name: Preper image in manifest
      run: sed -i 's|{{IMAGE}}|'"$IMAGE"':'"${GITHUB_SHA::7}"'|g' manifests/deployment.yaml

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
          manifests/ingress.yaml
        imagepullsecrets: 'demo-k8s-secret'
